url: http://jodaiber.de
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty
pygments: true
exclude: ['Rakefile.rb', 'CNAME', 'README.markdown']
