name: Update Instagram Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      IG_LONG_LIVED_TOKEN: ${{ secrets.IG_LONG_LIVED_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch latest media
        run: |
          mkdir -p assets
          curl -s "https://graph.instagram.com/me/media?fields=id,caption,media_url,permalink,thumbnail_url,media_type,timestamp&limit=12&access_token=${IG_LONG_LIVED_TOKEN}" > assets/instagram.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Instagram feed"
          branch: instagram-feed
          create_branch: true
